# Generated by Django 4.2.20 on 2025-05-31 23:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('facility_name', models.CharField(choices=[('restaurant', 'Restaurant'), ('room_service', 'Room service'), ('spa', 'Spa and wellness centre'), ('fitness_centre', 'Fitness Centre'), ('garden', 'Garden'), ('terrace', 'Terrace'), ('non_smoking_rooms', 'Non-smoking rooms'), ('airport_shuttle', 'Airport shuttle'), ('family_rooms', 'Family rooms'), ('free_wifi', 'Free WiFi'), ('air_conditioning', 'Air conditioning'), ('water_park', 'Water Park'), ('ev_charging', 'Electric vehicle charging station'), ('swimming_pool', 'Swimming pool'), ('beach', 'Beach'), ('electric_kettle', 'Electric Kettle'), ('tea_coffee_maker', 'Tea/Coffee maker'), ('dining_area', 'Dining area'), ('microwave', 'Microwave')], max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('hotel_name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=300)),
                ('description', models.TextField()),
                ('star_rating', models.IntegerField()),
                ('country', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('street_address', models.CharField(max_length=255)),
                ('postal_code', models.CharField(max_length=20)),
                ('check_in_from', models.TimeField()),
                ('check_in_until', models.TimeField()),
                ('check_out_from', models.TimeField()),
                ('check_out_until', models.TimeField()),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('parking', models.CharField(choices=[('free', 'Yes, free'), ('paid', 'Yes, paid'), ('no', 'No')], default='no', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('facilities', models.ManyToManyField(related_name='hotels', to='pages.facility')),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price_per_night', models.DecimalField(decimal_places=2, max_digits=10)),
                ('available_rooms', models.IntegerField()),
                ('adult_capacity', models.IntegerField()),
                ('room_size', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Room_animates',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('animation_name', models.CharField(choices=[('Clothes Rack', 'Clothes Rack'), ('Flat Screen TV', 'Flat Screen TV'), ('Air Conditioning', 'Air Conditioning'), ('Desk', 'Desk'), ('Wake Up Service', 'Wake Up Service'), ('Towels', 'Towels'), ('Wardrobe or Closet', 'Wardrobe or Closet'), ('Heating', 'Heating'), ('Fan', 'Fan'), ('Safety Deposit Box', 'Safety Deposit Box'), ('Extra Towels Fee', 'Extra Towels Fee'), ('Ground Floor Unit', 'Ground Floor Unit')], max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='profile_images/')),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RoomPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='room_images/')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.room')),
            ],
        ),
        migrations.AddField(
            model_name='room',
            name='animations',
            field=models.ManyToManyField(blank=True, to='pages.room_animates'),
        ),
        migrations.AddField(
            model_name='room',
            name='hotel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='pages.hotel'),
        ),
        migrations.AddField(
            model_name='room',
            name='room_facilities',
            field=models.ManyToManyField(related_name='rooms', to='pages.room_animates'),
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField()),
                ('comment', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='pages.hotel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='HotelPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='hotel_images/')),
                ('is_main', models.BooleanField(default=False)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hotel_images', to='pages.hotel')),
            ],
        ),
        migrations.CreateModel(
            name='Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visa', models.BooleanField(default=False)),
                ('mastercard', models.BooleanField(default=False)),
                ('meeza_card', models.BooleanField(default=False)),
                ('cash_on_delivery', models.BooleanField(default=False)),
                ('etsalat_cash', models.BooleanField(default=False)),
                ('aman_payment', models.BooleanField(default=False)),
                ('orange_cash', models.BooleanField(default=False)),
                ('vodafone_cash', models.BooleanField(default=False)),
                ('fawny_pay', models.BooleanField(default=False)),
                ('allow_children', models.BooleanField(default=False)),
                ('allow_pets', models.BooleanField(default=False)),
                ('hotel', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='pages.hotel')),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=100)),
                ('zip_code', models.CharField(blank=True, max_length=20, null=True)),
                ('country', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to='pages.hotel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_hotels', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'hotel')},
            },
        ),
    ]
