# Generated by Django 5.2.1 on 2025-05-17 09:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('facility_name', models.CharField(choices=[('wifi', 'WiFi'), ('parking', 'Parking'), ('pool', 'Pool'), ('gym', 'Gym'), ('spa', 'Spa'), ('restaurant', 'Restaurant'), ('bar', 'Bar'), ('room_service', 'Room Service'), ('laundry', 'Laundry'), ('business_center', 'Business Center'), ('conference_room', 'Conference Room'), ('pet_friendly', 'Pet Friendly'), ('airport_shuttle', 'Airport Shuttle'), ('beach_access', 'Beach Access'), ('family_friendly', 'Family Friendly'), ('non_smoking_rooms', 'Non Smoking Rooms')], max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Room_animates',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('animation_name', models.CharField(choices=[('swimming', 'Swimming'), ('dancing', 'Dancing'), ('singing', 'Singing'), ('yoga', 'Yoga'), ('cooking', 'Cooking'), ('painting', 'Painting'), ('crafting', 'Crafting'), ('gaming', 'Gaming'), ('sports', 'Sports'), ('photography', 'Photography'), ('music', 'Music'), ('theater', 'Theater'), ('comedy', 'Comedy'), ('magic', 'Magic'), ('storytelling', 'Storytelling'), ('workshops', 'Workshops'), ('fitness', 'Fitness'), ('meditation', 'Meditation'), ('adventure', 'Adventure'), ('exploration', 'Exploration'), ('cultural', 'Cultural'), ('nature', 'Nature'), ('wellness', 'Wellness'), ('relaxation', 'Relaxation')], max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('hotel_name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=300)),
                ('description', models.TextField()),
                ('star_rating', models.IntegerField()),
                ('country', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('street_address', models.CharField(max_length=255)),
                ('postal_code', models.CharField(max_length=20)),
                ('parking', models.CharField(choices=[('free', 'Yes, free'), ('paid', 'Yes, paid'), ('no', 'No')], default='no', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('facilities', models.ManyToManyField(related_name='hotels', to='pages.facility')),
            ],
        ),
        migrations.CreateModel(
            name='Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visa', models.BooleanField(default=False)),
                ('mastercard', models.BooleanField(default=False)),
                ('meeza_card', models.BooleanField(default=False)),
                ('cash_on_delivery', models.BooleanField(default=False)),
                ('etsalat_cash', models.BooleanField(default=False)),
                ('aman_payment', models.BooleanField(default=False)),
                ('orange_cash', models.BooleanField(default=False)),
                ('vodafone_cash', models.BooleanField(default=False)),
                ('fawny_pay', models.BooleanField(default=False)),
                ('allow_children', models.BooleanField(default=False)),
                ('allow_pets', models.BooleanField(default=False)),
                ('hotel', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='pages.hotel')),
            ],
        ),
        migrations.CreateModel(
            name='HotelPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='hotel_images/')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hotel_images', to='pages.hotel')),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price_per_night', models.DecimalField(decimal_places=2, max_digits=10)),
                ('available_rooms', models.IntegerField()),
                ('adult_capacity', models.IntegerField()),
                ('room_size', models.CharField(max_length=50)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='pages.hotel')),
                ('room_facilities', models.ManyToManyField(related_name='rooms', to='pages.room_animates')),
            ],
        ),
        migrations.CreateModel(
            name='RoomPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='room_images/')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.room')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField()),
                ('comment', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='pages.hotel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('hotel', 'user')},
            },
        ),
    ]
