# Generated by Django 5.1.7 on 2025-05-21 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facility',
            name='facility_name',
            field=models.CharField(choices=[('restaurant', 'Restaurant'), ('room_service', 'Room service'), ('spa', 'Spa and wellness centre'), ('fitness_centre', 'Fitness Centre'), ('garden', 'Garden'), ('terrace', 'Terrace'), ('non_smoking_rooms', 'Non-smoking rooms'), ('airport_shuttle', 'Airport shuttle'), ('family_rooms', 'Family rooms'), ('hot_tub', 'Hot tub/Jacuzzi'), ('free_wifi', 'Free WiFi'), ('air_conditioning', 'Air conditioning'), ('water_park', 'Water Park'), ('ev_charging', 'Electric vehicle charging station'), ('swimming_pool', 'Swimming pool'), ('beach', 'Beach'), ('electric_kettle', 'Electric Kettle'), ('tea_coffee_maker', 'Tea/Coffee maker'), ('dining_area', 'Dining area'), ('microwave', 'Microwave')], max_length=100),
        ),
        migrations.AlterField(
            model_name='room_animates',
            name='animation_name',
            field=models.CharField(choices=[('clothes_rack', 'Clothes Rack'), ('flat_screen_tv', 'Flat Screen TV'), ('air_conditioning', 'Air Conditioning'), ('desk', 'Desk'), ('wake_up_service', 'Wake Up Service'), ('towels', 'Towels'), ('wardrobe_or_closet', 'Wardrobe or Closet'), ('heating', 'Heating'), ('fan', 'Fan'), ('safety_deposit_box', 'Safety Deposit Box'), ('extra_towels_fee', 'Extra Towels Fee'), ('ground_floor_unit', 'Ground Floor Unit')], max_length=100),
        ),
    ]
