# Generated by Django 5.1.7 on 2025-05-25 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='main_image',
            field=models.ImageField(blank=True, null=True, upload_to='hotel_main_images/'),
        ),
    ]
