# Generated by Django 5.2.1 on 2025-05-18 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facility',
            name='facility_name',
            field=models.CharField(choices=[('wifi', 'WiFi'), ('Parking', 'Parking'), ('Pool', 'Pool'), ('Gym', 'Gym'), ('Spa', 'Spa'), ('Restaurant', 'Restaurant'), ('Bar', 'Bar'), ('Room Service', 'Room Service'), ('Laundry', 'Laundry'), ('Business Center', 'Business Center'), ('Conference Room', 'Conference Room'), ('Pet Friendly', 'Pet Friendly'), ('Airport shuttle', 'Airport Shuttle'), ('Beach Access', 'Beach Access'), ('Family Friendly', 'Family Friendly'), ('Non Smoking Rooms', 'Non Smoking Rooms')], max_length=100),
        ),
    ]
