# Generated by Django 5.2.1 on 2025-05-26 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facility',
            name='facility_name',
            field=models.CharField(choices=[('restaurant', 'Restaurant'), ('room_service', 'Room service'), ('spa', 'Spa and wellness centre'), ('fitness_centre', 'Fitness Centre'), ('garden', 'Garden'), ('terrace', 'Terrace'), ('non_smoking_rooms', 'Non-smoking rooms'), ('airport_shuttle', 'Airport shuttle'), ('family_rooms', 'Family rooms'), ('free_wifi', 'Free WiFi'), ('air_conditioning', 'Air conditioning'), ('water_park', 'Water Park'), ('ev_charging', 'Electric vehicle charging station'), ('swimming_pool', 'Swimming pool'), ('beach', 'Beach'), ('electric_kettle', 'Electric Kettle'), ('tea_coffee_maker', 'Tea/Coffee maker'), ('dining_area', 'Dining area'), ('microwave', 'Microwave')], max_length=100),
        ),
    ]
