# Generated by Django 5.1.7 on 2025-05-20 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotel',
            name='check_in_from',
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='check_in_until',
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='check_out_from',
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='check_out_until',
        ),
    ]
