# Generated by Django 5.1.7 on 2025-05-10 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotel',
            name='available_from',
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='available_to',
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='capacity',
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='location',
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='price_per_night',
        ),
        migrations.AddField(
            model_name='hotel',
            name='address',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='hotel',
            name='city',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='hotel',
            name='country',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='hotel',
            name='created_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='hotel',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hotel',
            name='stars',
            field=models.PositiveIntegerField(default=3, null=True),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
