# Generated by Django 4.2.20 on 2025-06-02 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_userprofile_is_admin_userprofile_is_superuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_method', models.CharField(choices=[('mastercard', 'MasterCard'), ('paypal', 'PayPal'), ('visa', 'Visa')], max_length=20)),
                ('card_number', models.CharField(max_length=16)),
                ('expiration', models.CharField(max_length=4)),
                ('security_code', models.CharField(max_length=4)),
                ('full_name', models.CharField(max_length=100)),
                ('birth_date', models.DateField()),
                ('country', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('billing_address', models.CharField(max_length=255)),
                ('zip_code', models.CharField(blank=True, max_length=20, null=True)),
                ('phone', models.CharField(max_length=15)),
                ('remember', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
