# Generated by Django 5.1.7 on 2025-05-20 18:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_remove_hotel_check_in_from_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='animations',
            field=models.ManyToManyField(blank=True, to='pages.room_animates'),
        ),
        migrations.AlterUniqueTogether(
            name='review',
            unique_together={('hotel', 'user')},
        ),
    ]
