# Generated by Django 5.1.7 on 2025-05-10 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_remove_hotel_available_from_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='location',
            field=models.CharField(null=True),
        ),
    ]
