# Generated by Django 5.1.7 on 2025-05-16 17:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_alter_hotel_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Facilities',
            new_name='Facility',
        ),
        migrations.RenameModel(
            old_name='Animations',
            new_name='Room_animates',
        ),
        migrations.RenameModel(
            old_name='RoomImage',
            new_name='RoomPhoto',
        ),
        migrations.RemoveField(
            model_name='hotelimage',
            name='hotel',
        ),
        migrations.AlterUniqueTogether(
            name='roomanimations',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='roomanimations',
            name='animation',
        ),
        migrations.RemoveField(
            model_name='roomanimations',
            name='room',
        ),
        migrations.RemoveField(
            model_name='room',
            name='room_type',
        ),
        migrations.AddField(
            model_name='hotel',
            name='check_in_from',
            field=models.TimeField(default='14'),
        ),
        migrations.AddField(
            model_name='hotel',
            name='check_in_until',
            field=models.TimeField(default='14'),
        ),
        migrations.AddField(
            model_name='hotel',
            name='check_out_from',
            field=models.TimeField(default='14'),
        ),
        migrations.AddField(
            model_name='hotel',
            name='check_out_until',
            field=models.TimeField(default='14'),
        ),
        migrations.AddField(
            model_name='hotel',
            name='city',
            field=models.CharField(null=True),
        ),
        migrations.AddField(
            model_name='hotel',
            name='country',
            field=models.CharField(null=True),
        ),
        migrations.AddField(
            model_name='hotel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='hotel',
            name='facilities',
            field=models.ManyToManyField(related_name='hotels', to='pages.facility'),
        ),
        migrations.AddField(
            model_name='hotel',
            name='parking',
            field=models.CharField(choices=[('free', 'Yes, free'), ('paid', 'Yes, paid'), ('no', 'No')], default='no', max_length=10),
        ),
        migrations.AddField(
            model_name='hotel',
            name='postal_code',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='hotel',
            name='street_address',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='room_facilities',
            field=models.ManyToManyField(null=True, related_name='rooms', to='pages.room_animates'),
        ),
        migrations.AddField(
            model_name='room',
            name='room_size',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='hotel_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='location',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='star_rating',
            field=models.IntegerField(max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='adult_capacity',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='available_rooms',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='hotel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='pages.hotel'),
        ),
        migrations.AlterField(
            model_name='room',
            name='price_per_night',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.CreateModel(
            name='Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visa', models.BooleanField(default=False)),
                ('mastercard', models.BooleanField(default=False)),
                ('meeza_card', models.BooleanField(default=False)),
                ('cash_on_delivery', models.BooleanField(default=False)),
                ('etsalat_cash', models.BooleanField(default=False)),
                ('aman_payment', models.BooleanField(default=False)),
                ('orange_cash', models.BooleanField(default=False)),
                ('vodafone_cash', models.BooleanField(default=False)),
                ('fawny_pay', models.BooleanField(default=False)),
                ('allow_children', models.BooleanField(default=False)),
                ('allow_pets', models.BooleanField(default=False)),
                ('hotel', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='pages.hotel')),
            ],
        ),
        migrations.CreateModel(
            name='HotelPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='hotel_images/')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hotel_images', to='pages.hotel')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField()),
                ('comment', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='pages.hotel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('hotel', 'user')},
            },
        ),
        migrations.DeleteModel(
            name='HotelFacilities',
        ),
        migrations.DeleteModel(
            name='HotelImage',
        ),
        migrations.DeleteModel(
            name='RoomAnimations',
        ),
    ]
