# Generated by Django 5.1.7 on 2025-05-21 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_alter_facility_facility_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='check_in_until',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='hotel',
            name='check_out_from',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='check_in_from',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='check_out_until',
            field=models.TimeField(null=True),
        ),
    ]
