# Generated by Django 5.2.1 on 2025-05-30 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_alter_facility_facility_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room_animates',
            name='animation_name',
            field=models.CharField(choices=[('Clothes Rack', 'Clothes Rack'), ('Flat Screen TV', 'Flat Screen TV'), ('Air Conditioning', 'Air Conditioning'), ('Desk', 'Desk'), ('Wake Up Service', 'Wake Up Service'), ('Towels', 'Towels'), ('Wardrobe or Closet', 'Wardrobe or Closet'), ('Heating', 'Heating'), ('Fan', 'Fan'), ('Safety Deposit Box', 'Safety Deposit Box'), ('Extra Towels Fee', 'Extra Towels Fee'), ('Ground Floor Unit', 'Ground Floor Unit')], max_length=100),
        ),
    ]
