# Generated by Django 5.1.7 on 2025-05-17 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_rename_facilities_facility_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='room_facilities',
        ),
        migrations.AddField(
            model_name='room',
            name='animations',
            field=models.ManyToManyField(blank=True, to='pages.room_animates'),
        ),
    ]
