# Generated by Django 5.1.7 on 2025-05-18 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_remove_room_room_facilities_room_animations'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='hotel',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='check_in_from',
            field=models.TimeField(default='14:00'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='check_in_until',
            field=models.TimeField(default='14:00'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='check_out_from',
            field=models.TimeField(default='14:00'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='check_out_until',
            field=models.TimeField(default='14:00'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='city',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='country',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='star_rating',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='hotelphoto',
            name='image',
            field=models.ImageField(upload_to='hotel_images/'),
        ),
    ]
