# Generated by Django 5.1.7 on 2025-06-03 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_alter_hotel_owner'),
        ('pages', '0005_chatmessage'),
    ]

    operations = [
    ]
